language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t hbaj/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hbaj/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react-ebs-app"
  env: "Dockerreactebsapp-env"
  bucket_name: "elasticbeanstalk-eu-west-2-760029521526"
  bucket_path: "docker-react-ebs-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY